# Generated by Django 5.2 on 2025-05-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_reservation_name_reservation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
    ]
