# Generated by Django 5.2 on 2025-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='benevole',
            field=models.BooleanField(default=False),
        ),
    ]
