# Generated by Django 5.2 on 2025-05-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_reservation_status_reservation_benevole'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='ID utilisateur'),
        ),
    ]
