# Generated by Django 5.2 on 2025-05-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customuser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('EDS', 'EDS'), ('Autre', 'Autre')], max_length=10)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'category')},
            },
        ),
    ]
