# Generated by Django 5.2 on 2025-05-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mealreservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MealReservation',
            new_name='Reservation',
        ),
    ]
